FROM openjdk:8-jdk-alpine
ARG AWS_ACCESS_KEY_ID
ARG AWS_SECRET_ACCESS_KEY
ARG AWS_REGION
ARG BUCKET_NAME
ENV AWS_ACCESS_KEY_ID="$AWS_ACCESS_KEY_ID"
ENV AWS_SECRET_ACCESS_KEY="$AWS_SECRET_ACCESS_KEY"
ENV AWS_REGION="$AWS_REGION"
ENV BUCKET_NAME="$BUCKET_NAME"
EXPOSE ${AWS_ACCESS_KEY_ID}
EXPOSE ${AWS_SECRET_ACCESS_KEY}
EXPOSE ${AWS_REGION}
EXPOSE ${BUCKET_NAME}
VOLUME /tmp
COPY target/listings-service-0.0.1-SNAPSHOT.jar  app.jar
ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom","-jar","/app.jar"]
