---
kind: Service
apiVersion: v1
metadata:
  name: listings-service
  labels:
    app: listings
spec:
  ports:
    - port: 8080
      targetPort: api
  selector:
    app: listings
  type: LoadBalancer
